[project]
name = "python-vectorspace"
version = "0.0.3"
authors = [
  { name="deathbeam", email="slusnucky@gmail.com" },
]
description = "Directory file watcher for automatically creating and querying vector embeddings."
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "chromadb>=0.6.3",
    "fastapi>=0.115.11",
    "sentence-transformers>=3.4.1",
    "uvicorn>=0.34.0",
    "watchdog>=6.0.0",
]

[project.urls]
Homepage = "https://github.com/deathbeam/vectorspace"
Issues = "https://github.com/deathbeam/vectorspace/issues"

[project.scripts]
vectorspace = "vectorspace.app:main"
